### ISSUE TITLE
Demo of how to implement (hosted as CDN or localhost)?

### ISSUE THREAD

**Issue by ffd8** [gkjohnson/ldraw-parts-library#1]
I stumbled across your tweet (amazing rendering!) and this repo of the hosted parts... any tips on how to have a very minimal renderer of .mpd files for local host?? I have a student who is exploring ldraw files and glitching them for fun exploration... finding bits and pieces of viewer code/demos, but can't get them working just yet with the `/ldraw`, `/parts` etc.. seems like you have a workflow – so any insights to the basic setup with threejs combined with its LDrawLoader add-on would be super helpful! Thanks in advance!

FYI, followed the three.js install instructions for npm + vite, currently have the following in our `main.js`, first tried loading as as CDN to your hosted parts library, then also tried loading locally within the same dir:

index.html:
```HTML
<!DOCTYPE html> 
<html lang="en"> 
	<head> 
		<meta charset="utf-8"> 
		<title>My first three.js app</title> 
		<style> body { margin: 0; } </style> 
	</head> 
	<body>
		<script type="module" src="/main.js"></script> 
	</body> 
</html>
```
main.js:
```JS
import * as THREE from 'three';
import { LDrawLoader } from 'three/addons/loaders/LDrawLoader.js';

const loader = new LDrawLoader();
loader.setPartsLibraryPath( 'ldraw/' );
await loader.preloadMaterials( 'ldcfgalt.ldr' );

loader.load( '10183-1.mpd' );

```

**Comment by gkjohnson** [comment]
Hello! I can't help you with vite or build processes but I've used these parts via github links:

```js
const loader = new LDrawLoader( manager );
await loader.preloadMaterials( 'https://raw.githubusercontent.com/gkjohnson/ldraw-parts-library/master/colors/ldcfgalt.ldr' );
loader
    .setPartsLibraryPath( 'https://raw.githubusercontent.com/gkjohnson/ldraw-parts-library/master/complete/ldraw/' )
    .load( url, ... );
```

You'll have to adjust this if you want to load from a local copy of the data.
